### PR TITLE
V1.2 Changing MedHistory to use Set

### PR DESCRIPTION
**Pull request by xShaivan**
Also modifying test files.

### CODE REVIEW

**Comment by xShaivan** [comment]
java.lang.AssertionError at XmlUtilTest.java:89
java.lang.AssertionError at XmlUtilTest.java:98
java.lang.AssertionError at XmlUtilTest.java:107

// The below code fails
assertEquals(expectedPerson, actualPerson);

**Comment by xShaivan** [comment]
java.lang.AssertionError at XmlUtilTest.java:89 (resolved)
java.lang.AssertionError at XmlUtilTest.java:98 (resolved)
java.lang.AssertionError at XmlUtilTest.java:107 (unresolved)

**Comment by xShaivan** [comment]
XmlUtilTest.java fully resolved.

Now trying to resolve:
java.lang.AssertionError at EditCommandSystemTest.java:270

**Comment by brandonccm1996** [comment]
Good job changing med history to a set of med histories

**Pull request merged**
